for review
mate-academy/js_double-trouble pull request #41
Opened 2019-06-15 14:35 UTC by Hlybchenko

2019-06-17 18:43 UTC, vpolets approved these changes

2019-06-18 12:21 UTC, vpolets requested changes

2019-06-18 12:21 UTC, vpolets commented on src/doubleTrouble.js
> +  return array;
міняти вхідний масив - погана практика

2019-06-19 06:10 UTC, vpolets requested changes

2019-06-19 06:10 UTC, vpolets commented on src/doubleTrouble.js
> +  const matchedDigits = array;
Це не копія!

2019-06-19 09:52 UTC, vkryvytskyi approved these changes

2026-03-06 11:28 UTC, closed without merging